# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the FTS Capacitive touchscreen driver APIs.
#

obj-y += ftsCompensation.o ftsCore.o ftsError.o ftsFrame.o ftsIO.o ftsTest.o ftsTime.o ftsTool.o ftsFlash.o ftsGesture.o

